### PR TITLE
Customized Options: fixed selection closes #389

### LINKED ISSUE #389: Custom Option-Elements broken
Since v0.10.0-beta.0 options with custom elements are broken.

Example:
```handlebars
{{#power-select options=someList selected=selectedItem onchange=(action 'someAction') as |item|}}
  <div class="special-class">
    <i class={{item.icon}}></i>
    {{item.text}}
  </div>
{{/power-select}}
```

If you click on the 'i'-Tag in the list, nothing happens.
After some investigation i found out, why it doesn't work:

[addon/components/power-select/options Line 19](https://github.com/cibernox/ember-power-select/blob/74202ee25bc189883edca130b75c76eb2eec9410/addon/components/power-select/options.js#L19)
```javascript
this.element.addEventListener('mouseup', e => {
  if (e.target.dataset.optionIndex) { // the clicked element 'i' doesn't have a data-option-index property
    this.get('select.actions.choose')(this._optionFromIndex(e.target.dataset.optionIndex), e);
  }
});
```

The clicked 'i' doesn't have a 'data-option-index'-Property, so the if gets passed by and nothing happens.

That could be solved with the little help of jquery:
```javascript
this.element.addEventListener('mouseup', e => {
  const optionIndex = Ember.$(e.target).closest('li').data('option-index').toString();
  if(!isEmpty(optionIndex)){
    this.get('select.actions.choose')(this._optionFromIndex(optionIndex), e);
  }
});
```

Maybe there is also another solution?

### PR DESCRIPTION
**Pull request by Haidy777**
see #389

### CODE REVIEW

File: addon/components/power-select/options.js [hunk 1]
```diff
@@ -16,8 +16,9 @@ export default Ember.Component.extend({
     if (this.get('role') === 'group') { return; }
 
     this.element.addEventListener('mouseup', e => {
-      if (e.target.dataset.optionIndex) {
-        this.get('select.actions.choose')(this._optionFromIndex(e.target.dataset.optionIndex), e);
+      const optionIndex = Ember.$(e.target).closest('li').data('option-index').toString();
```
Comment (cibernox) [inline addon/components/power-select/options.js]: Do you need the `toString`? 

What about...

```
let optionItem = e.target.closest('[data-option-index]');
if (!option) { return; }
this.get('select.actions.choose')(this._optionFromIndex(optionItem.dataset.optionIndex), e);
```

Comment (cibernox) [inline addon/components/power-select/options.js]: I prefer this in case the custom html inside the options contains (God knows why) more nested `<li>`s elements.

**Comment by cibernox** [comment]
Just one suggestion, to make sure this works even if there is nested `<li>`s in the markup.

**Comment by cibernox** [comment]
Failures in travis seem related to npm doing npm things. Should be fine the next time.

**Comment by Haidy777** [comment]
Well, didn't think about nested ```li```s. Good point ;)
```.toString()``` is only needed because ```.data``` returns a Number (in this case).

Just updated the commit.

**Comment by cibernox** [comment]
Thanks!

**Comment by cibernox** [comment]
Released a new beta
